imports:
  common: ./common.yml
types:
  Rule:
    properties:
      path: string
      base: string
      serviceName: string
  Ingress:
    properties:
      name: string
      namespace: string
      rules: optional<list<Rule>>
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
  Path:
    properties:
      path: string
      base: string
      port: optional<string>
      serviceName: string
      serviceNamespace: string
  Gateway:
    properties:
      name: string
      namespace: string
  HttpRoute:
    properties:
      name: string
      namespace: string
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
      gateways: optional<list<Gateway>>
      paths: optional<list<Path>>
  IngressReport:
    properties:
      httpRoutes: optional<list<HttpRoute>>
      ingresses: optional<list<Ingress>>
      clusterUrl: optional<string>
      authType: common.AuthTypes
      errors: optional<list<string>>