imports:
  common: ./common.yml
types:
  RouteInfo:
    properties:
      path: string
      base: string
      port: optional<string>
      service: common.ServiceInfo
  GatewayInfo:
    properties:
      uid: string
      name: string
      namespace: common.NamespaceInfo
  HttpRoute:
    properties:
      uid: string
      name: string
      namespace: common.NamespaceInfo
      gateways: optional<list<GatewayInfo>>
      paths: optional<list<RouteInfo>>
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
  Ingress:
    properties:
      uid: string
      name: string
      namespace: common.NamespaceInfo
      rules: optional<list<RouteInfo>>
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
  LoadBalancer:
   properties:
      uid: string
      name: string
      namespace: common.NamespaceInfo
      paths: optional<list<RouteInfo>>
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
  IngressReport:
    properties:
      httpRoutes: optional<list<HttpRoute>>
      ingresses: optional<list<Ingress>>
      loadBalancers: optional<list<LoadBalancer>>
      clusterUrl: optional<string>
      authType: common.AuthTypes
      errors: optional<list<string>>