imports:
  common: ./common.yml
types:
  Rule:
    properties:
      host: string
      path: string
      serviceName: string
      servicePort: optional<string>
  Ingress:
    properties:
      name: string
      namespace: string
      rules: optional<list<Rule>>
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
  Gateway:
    properties:
      name: string
      namespace: string
      listeners: list<string>
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
  IngressReport:
    properties:
      gateways: optional<list<Gateway>>
      ingresses: optional<list<Ingress>>
      clusterUrl: optional<string>
      errors: optional<list<string>>