imports:
  common: ./common.yml
types:
  ServicePort:
    properties:
      name: string
      protocol: common.ProtocolTypes
      port: integer
      targetPort: string
  Service: 
    properties:
      name: string
      namespace: string
      type: string
      managedBy: string
      ports: list<ServicePort>
  ServiceReport:
    properties:
      services: optional<list<Service>>
      errors: optional<list<string>>