imports:
  common: ./common.yml
types:
  Service: 
    properties:
      name: string
      namespace: common.NamespaceInfo
      type: string
      pods: optional<list<string>>
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
      selectors: optional<map<string, string>>
  ServiceReport:
    properties:
      services: optional<list<Service>>
      clusterUrl: optional<string>
      authType: common.AuthTypes
      errors: optional<list<string>>