imports:
  common: ./common.yml
types:
  Service: 
    properties:
      name: string
      namespace: string
      type: string
      managedBy: optional<string>
      pods: optional<list<string>>
      annotations: optional<map<string, string>>
      labels: optional<map<string, string>>
      selectors: optional<map<string, string>>
  ServiceReport:
    properties:
      services: optional<list<Service>>
      clusterUrl: optional<string>
      errors: optional<list<string>>